# Configuration based on https://github.com/korfuri/bazel-travis
sudo: false

os: linux
dist: xenial
language: python
python:
  - "3.6"

# cache:
#   directories:
#     - $HOME/.bazelcache

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  # - sudo chown -R travis:travis /home/travis/
  - pip install codecov
  - curl -L -o bbazel-0.25.2-installer-linux-x86_64.sh https://github.com/bazelbuild/bazel/releases/download/0.25.2/bazel-0.25.2-installer-linux-x86_64.sh
  - chmod +x bazel-0.25.2-installer-linux-x86_64.sh
  - ./bazel-0.25.2-installer-linux-x86_64.sh

script:
  # - bazel build examples/... --experimental_repository_cache=$HOME/.bazelcache
  - bazel build //colugo:all
  - bazel test --test_output=errors --noshow_progress //colugo:all
  - coverage run ./bazel-bin/colugo/test_node

after_success:
  - codecov
