# Configuration based on https://github.com/korfuri/bazel-travis
# sudo: false

os: linux
dist: xenial

language: python
python:
  - "3.6"

# cache:
#   directories:
#   - $HOME/.cache/bazel

install:
  - pip install -r requirements.txt

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg"
    packages:
      - oracle-java8-installer
      - bazel

# before_install: skip
#   - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
#   - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
#   - apt-get update && sudo apt-get install bazel
#   #- wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel-0.11.1-without-jdk-installer-linux-x86_64.sh
#   #- sha256sum -c tools/bazel_0.11.1-without-jdk-installer-linux-x86_64.sh.sha256
#   #- chmod +x bazel-0.11.1-without-jdk-installer-linux-x86_64.sh
#   #- ./bazel-0.11.1-without-jdk-installer-linux-x86_64.sh --user

script:
  - bazel build examples/...
  - bazel test --test_output=errors --noshow_progress colugo/...
