# Configuration based on https://github.com/korfuri/bazel-travis
sudo: false

os: linux
dist: xenial

language: python
python:
  - "3.6"

# command to install dependencies
# virtualenv is activated by default when specifying language: python
install:
  - pip install -r requirements.txt

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel-0.11.1-without-jdk-installer-darwin-x86_64.sh
  - sha256sum -c tools/bazel_0.11.1-without-jdk-installer-darwin-x86_64.sh.sha256
  - chmod +x bazel-0.11.1-without-jdk-installer-linux-x86_64.sh
  - ./bazel-0.11.1-without-jdk-installer-linux-x86_64.sh --user

script:
  - bazel build examples/...
  - bazel test --test_output=errors --noshow_progress colugo/...
