# Configuration based on https://github.com/korfuri/bazel-travis
sudo: required

os: linux
dist: xenial
language: python
python:
  - "3.6"

cache:
  directories:
  - $HOME/.cache/bazel

# jdk:
#   - &jdk_for_publishing oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget

before_install: skip
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel_0.11.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.11.1-linux-x86_64.deb

script:
  - bazel build examples/...
  - bazel test --test_output=errors --noshow_progress colugo/...
