# Configuration based on https://github.com/korfuri/bazel-travis

os: linux
dist: xenial

language: python
python:
  - "3.6"

# command to install dependencies
# virtualenv is activated by default when specifying language: python
install:
  - pip install -r requirements.txt

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - wget
#       - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel_0.11.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.11.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.11.1-linux-x86_64.deb

script:
  - bazel build examples/...
