# Configuration based on https://github.com/korfuri/bazel-travis
sudo: required

os: linux
dist: xenial
language: python
python:
  - "3.6"

cache:
  directories:
  - $HOME/.cache/bazel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel_0.11.1-linux-x86_64.deb
  - sha256sum -c tools/bazel_0.11.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.11.1-linux-x86_64.deb

script:
  - bazel build examples/...
  - bazel test --test_output=errors --noshow_progress colugo/...
