py_binary(
    name = "pub",
    srcs = ["py/pub.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//colugo:colugo_py",
    ],
)

py_binary(
    name = "sub",
    srcs = ["py/sub.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//colugo:colugo_py",
    ],
)

py_binary(
    name = "req",
    srcs = ["py/req.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//colugo:colugo_py",
    ],
)

py_binary(
    name = "rep",
    srcs = ["py/rep.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//colugo:colugo_py",
    ],
)
